#!/bin/bash
set +e

logpath=$1
debug=$2

if [ ! -d "$logpath" -o -z "$logpath" ]; then 
cat << EOF
Usage:	
	$0 log_path_directory
EOF
  exit
fi


for file in $(find $logpath -maxdepth 1 -type f -name "*.$(hostname).*.log.*.2*"); do
	lsof -- $file > /dev/null
	if [ $? -eq 0 ]; then
		echo File $file is in use. Skipping...
	else 
		path=${file%/*}/
		name=${file##*/}
		newpath=${logpath}/$(echo $name | sed 's,\(.*\)\.chains1\.\(.*\)\.log\.\(.*\)\.\(2[0-9]\{3\}\)\([0-9][0-9]\)\([0-9][0-9]\)\(.*\),\4/\5/\6/\1.\3,g')
		mkdir -p $newpath
		mv $file $newpath
#		echo -n .
	fi
done

